spring.application.name=foodiesapi

spring.mongodb.uri=${MONGODB_URL}

spring.data.mongodb.ssl.enabled=true

aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-southeast-2
aws.s3.bucketname=foodies-foods3

jwt.secret.key=${JWT_SECRET_KEY}